
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('WTF').del()
    .then(function () {
      // Inserts seed entries
      return knex('WTF').insert([

        { Name: "?", Desc: "I don't understand what you mean" },
        { Name: "?4U", Desc: "I have a question for you" },
        { Name: ";S", Desc: "Gentle warning, like 'Hmm? What did you say?'" },
        { Name: "^^", Desc: "Meaning 'read line' or 'read message' above" },
        { Name: "&lt;3", Desc: "Meaning 'sideways heart' (love, friendship)" },
        { Name: "&lt;33", Desc: "Meaning 'heart or love' (more 3s is a bigger heart)" },
        { Name: "@TEOTD", Desc: "At the end of the day" },
        { Name: "0.02", Desc: "My (or your) two cents worth" },
        { Name: "1TG, 2TG", Desc: "Meaning number of items needed for win (online gaming)" },
        { Name: "1UP", Desc: "Meaning extra life (online gaming)" },
        { Name: "121", Desc: "One-to-one (private chat initiation)" },
        { Name: "1337", Desc: "Leet, meaning 'elite'" },
        { Name: "143", Desc: "I love you" },
        { Name: "1432", Desc: "I love you too" },
        { Name: "14AA41", Desc: "One for all, and all for one" },
        { Name: "182", Desc: "I hate you" },
        { Name: "19", Desc: "Zero hand (online gaming)" },
        { Name: "10M", Desc: "Ten man (online gaming)" },
        { Name: "10X", Desc: "Thanks" },
        { Name: "10Q", Desc: "Thank you" },
        { Name: "1CE", Desc: "Once" },
        { Name: "1DR", Desc: "I wonder" },
        { Name: "1NAM", Desc: "One in a million" },
        { Name: "2", Desc: "Meaning 'to' in SMS" },
        { Name: "20", Desc: "Meaning 'location'" },
        { Name: "2B", Desc: "To be" },
        { Name: "2EZ", Desc: "Too easy" },
        { Name: "2G2BT", Desc: "Too good to be true" },
        { Name: "2M2H", Desc: "Too much too handle" },
        { Name: "2MI", Desc: "Too much information" },
        { Name: "2MOR", Desc: "Tomorrow" },
        { Name: "2MORO", Desc: "Tomorrow" },
        { Name: "2M2H", Desc: "Too much to handle" },
        { Name: "2N8", Desc: "Tonight" },
        { Name: "2NTE", Desc: "Tonight" },
        { Name: "4", Desc: "Short for 'for' in SMS" },
        { Name: "411", Desc: "Meaning 'information'" },
        { Name: "404", Desc: "I don't know" },
        { Name: "411", Desc: "Meaning 'information'" },
        { Name: "420", Desc: "Lets get high" },
        { Name: "420", Desc: "Meaning 'Marijuana'" },
        { Name: "459", Desc: "Means I love you (ILY is 459 using keypad numbers)" },
        { Name: "4AO", Desc: "For adults only" },
        { Name: "4COL", Desc: "For crying out loud" },
        { Name: "4EAE", Desc: "Forever and ever&nbsp;" },
        { Name: "4EVA", Desc: "Forever" },
        { Name: "4NR", Desc: "Foreigner&nbsp;" },
        { Name: "4SALE", Desc: "For sale" },
        { Name: "^5", Desc: "High-five" },
        { Name: "511", Desc: "Too much information (more than 411)" },
        { Name: "555", Desc: "Sobbing, crying. (Mandarin Chinese txt msgs)" },
        { Name: "55555", Desc: "Crying your eyes out (Mandarin Chinese txt msgs)" },
        { Name: "55555", Desc: "Meaning Laughing (In Thai language the number 5 is pronounced 'ha'.)" },
        { Name: "6Y", Desc: "Sexy" },
        { Name: "7K", Desc: "Sick" },
        { Name: "81", Desc: "Meaning Hells Angels (H=8th letter of alphabet, A=1st letter of alphabet)" },
        { Name: "831", Desc: "I love you (8 letters, 3 words, 1 meaning)" },
        { Name: "86", Desc: "Over" },
        { Name: "88", Desc: "Bye-bye (Mandarin Chinese txt msgs)&nbsp;" },
        { Name: "88", Desc: "Hugs and kisses" },
        { Name: "9", Desc: "Parent is watching&nbsp;" },
        { Name: "*s*", Desc: "Meaning 'smile'" },
        { Name: "*w*", Desc: "Meaning 'wink'" },
        { Name: "A3", Desc: "Anytime, anywhere, anyplace" },
        { Name: "AA", Desc: "As above" },
        { Name: "AA", Desc: "Ask about" },
        { Name: "AAF", Desc: "As a matter of fact" },
        { Name: "AAF", Desc: "As a friend" },
        { Name: "AAK", Desc: "Asleep at keyboard" },
        { Name: "AAK", Desc: "Alive and kicking" },
        { Name: "AAMOF", Desc: "As a matter of fact" },
        { Name: "AAMOI", Desc: "As a matter of interest" },
        { Name: "AAP", Desc: "Always a pleasure" },
        { Name: "AAR", Desc: "At any rate" },
        { Name: "AAS", Desc: "Alive and smiling" },
        { Name: "AASHTA", Desc: "As always, Sheldon has the answer (Bike mechanic Sheldon Brown)" },
        { Name: "AATK", Desc: "Always at the keyboard" },
        { Name: "AAYF", Desc: "As always, your friend" },
        { Name: "ABBR", Desc: "Meaning abbreviation" },
        { Name: "ABC", Desc: "Already been chewed" },
        { Name: "ABD", Desc: "Already been done" },
        { Name: "ABT", Desc: "About" },
        { Name: "ABT2", Desc: "Meaning 'About to'" },
        { Name: "ABTA", Desc: "Meaning Good-bye (signoff)" },
        { Name: "ABU", Desc: "All bugged up" },
        { Name: "AC", Desc: "Acceptable content" },
        { Name: "ACC", Desc: "Anyone can come" },
        { Name: "ACD", Desc: "ALT / CONTROL / DELETE" },
        { Name: "ACDNT", Desc: "Accident (e-mail, Government)" },
        { Name: "ACE", Desc: "Meaning marijuana cigarette" },
        { Name: "ACK", Desc: "Acknowledge" },
        { Name: "ACPT", Desc: "Accept (e-mail, Government)" },
        { Name: "ACQSTN", Desc: "Acquisition (e-mail, Government)" },
        { Name: "ADAD", Desc: "Another day, another dollar" },
        { Name: "ADBB", Desc: "All done, bye-bye" },
        { Name: "ADD", Desc: "Address" },
        { Name: "ADDY", Desc: "Address" },
        { Name: "ADIH", Desc: "Another day in hell" },
        { Name: "ADIP", Desc: "Another day in paradise" },
        { Name: "ADMIN", Desc: "Administrator" },
        { Name: "ADMINR", Desc: "Administrator (Government)" },
        { Name: "ADN", Desc: "Any day now" },
        { Name: "ADR", Desc: "Address" },
        { Name: "AE", Desc: "Area effect (online gaming)" },
        { Name: "AEAP", Desc: "As early as possible" },
        { Name: "AF", Desc: "April Fools" },
        { Name: "AF", Desc: "As *Freak*" },
        { Name: "AF", Desc: "Aggression factor (online gaming)" },
        { Name: "AFC", Desc: "Away from computer" },
        { Name: "AFAIAA", Desc: "As far as I am aware" },
        { Name: "AFAIC", Desc: "As far as I am concerned" },
        { Name: "AFAIK", Desc: "As far as I know" },
        { Name: "AFAIUI", Desc: "As far as I understand it" },
        { Name: "AFAP", Desc: "As far as possible" },
        { Name: "AFFA", Desc: "Angels Forever, Forever Angels" },
        { Name: "AFJ", Desc: "April Fool's joke" },
        { Name: "AFK", Desc: "Away from keyboard" },
        { Name: "AFZ", Desc: "Acronym Free Zone" },
        { Name: "AFPOE", Desc: "A fresh pair of eyes" },
        { Name: "AGI", Desc: "Meaning 'agility' (online gaming)" },
        { Name: "AH", Desc: "At home" },
        { Name: "AIAMU", Desc: "And I am a money's uncle" },
        { Name: "AIGHT", Desc: "Alright" },
        { Name: "AIR", Desc: "As I remember" },
        { Name: "AISB", Desc: "As it should be" },
        { Name: "AISB", Desc: "As I said before" },
        { Name: "AISI", Desc: "As I see it" },
        { Name: "AITR", Desc: "Adult in the room" },
        { Name: "AKA", Desc: "Also known as" },
        { Name: "ALCON", Desc: "All concerned" },
        { Name: "ALOL", Desc: "Actually laughing out loud" },
        { Name: "AMA", Desc: "Ask me anything (Reddit)" },
        { Name: "AMAP", Desc: "As much as possible" },
        { Name: "AMBW", Desc: "All my best wishes" },
        { Name: "AML", Desc: "All my love" },
        { Name: "AMOF", Desc: "As a matter of fact" },
        { Name: "A/N", Desc: "Author's note" },
        { Name: "AO", Desc: "Anarchy Online (online gaming)" },
        { Name: "AOC", Desc: "Available on cell" },
        { Name: "AOE", Desc: "Area of effect (online game)" },
        { Name: "AOM", Desc: "Age of majority" },
        { Name: "AOM", Desc: "Age of Mythology (online gaming)" },
        { Name: "AOTA", Desc: "All of the above" },
        { Name: "AOYP", Desc: "Angel on your pillow" },
        { Name: "APAC", Desc: "All praise and credit" },
        { Name: "APP", Desc: "Application" },
        { Name: "APP", Desc: "Appreciate" },
        { Name: "AQAP", Desc: "As quick (or quiet) as possible" },
        { Name: "ARC", Desc: "Archive (compressed files)" },
        { Name: "ARE", Desc: "Acronym rich environment" },
        { Name: "ARG", Desc: "Argument" },
        { Name: "ASIG", Desc: "And so it goes" },
        { Name: "ASAP", Desc: "As soon as possible" },
        { Name: "A/S/L", Desc: "Age/sex/location" },
        { Name: "ASL", Desc: "Age/sex/location" },
        { Name: "ASLA", Desc: "Age/sex/location/availability" },
        { Name: "AT", Desc: "At your terminal" },
        { Name: "ATB", Desc: "All the best" },
        { Name: "ATEOTD", Desc: "At the end of the day" },
        { Name: "ATM", Desc: "At the moment" },
        { Name: "ATSITS", Desc: "All the stars in the sky" },
        { Name: "ATSL", Desc: "Along the same line (or lines)" },
        { Name: "AWC", Desc: "After awhile crocodile" },
        { Name: "AWESO", Desc: "Awesome" },
        { Name: "AWOL", Desc: "Away without leaving" },
        { Name: "AWOL", Desc: "Absent without leave" },
        { Name: "AYDY", Desc: "Are you done yet?" },
        { Name: "AYBABTU", Desc: "All your base are belong to us (online gaming)" },
        { Name: "AYEC", Desc: "At your earliest convenience" },
        { Name: "AYOR", Desc: "At your own risk" },
        { Name: "AYSOS", Desc: "Are you stupid or something?" },
        { Name: "AYS", Desc: "Are you serious?" },
        { Name: "AYT", Desc: "Are you there?" },
        { Name: "AYTMTB", Desc: "And you're telling me this because" },
        { Name: "AYV", Desc: "Are you vertical?" },
        { Name: "AYW", Desc: "As you were" },
        { Name: "AYW", Desc: "As you want / As you wish" },
        { Name: "AZN", Desc: "Asian" },
        { Name: "B", Desc: "Back" },
        { Name: "B", Desc: "Be" },
        { Name: "B&amp;", Desc: "Banned" },
        { Name: "B2W", Desc: "Back to work" },
        { Name: "B8", Desc: "Bait (person teased or joked with, or under-aged person/teen)" },
        { Name: "B9", Desc: "Boss is watching" },
        { Name: "B/F", Desc: "Boyfriend" },
        { Name: "B/G", Desc: "Background (personal information request)" },
        { Name: "B4", Desc: "Before" },
        { Name: "B4N", Desc: "Bye for now" },
        { Name: "BAG", Desc: "Busting a gut" },
        { Name: "BA", Desc: "Bad *a*" },
        { Name: "BAE", Desc: "Before anyone else" },
        { Name: "BAE", Desc: "Meaning Babe or baby" },
        { Name: "BAFO", Desc: "Best and final offer" },
        { Name: "BAK", Desc: "Back at keyboard" },
        { Name: "BAM", Desc: "Below average mentality" },
        { Name: "BAMF", Desc: "Bad *a* mother *f*" },
        { Name: "BAO", Desc: "Be aware of" },
        { Name: "BAS", Desc: "Big 'butt' smile" },
        { Name: "BASIC", Desc: "Meaning anything mainstream" },
        { Name: "BASOR", Desc: "Breathing a sigh of relief" },
        { Name: "BAU", Desc: "Business as usual" },
        { Name: "BAY", Desc: "Back at ya" },
        { Name: "BB", Desc: "Be back" },
        { Name: "BB", Desc: "Big brother" },
        { Name: "BB", Desc: "Bebi / Baby (Spanish SMS)" },
        { Name: "BBC", Desc: "Big bad challenge" },
        { Name: "BBIAB", Desc: "Be back in a bit" },
        { Name: "BBIAF", Desc: "Be back in a few" },
        { Name: "BBIAM", Desc: "Be back in a minute" },
        { Name: "BBIAS", Desc: "Be back in a sec" },
        { Name: "BBL", Desc: "Be back later" },
        { Name: "BBN", Desc: "Bye, bye now" },
        { Name: "BBQ", Desc: "Barbeque, 'Ownage', shooting score/frag (online gaming)" },
        { Name: "BBS", Desc: "Be back soon" },
        { Name: "BBT", Desc: "Be back tomorrow" },
        { Name: "BC", Desc: "Because" },
        { Name: "B/C", Desc: "Because" },
        { Name: "BC", Desc: "Be cool" },
        { Name: "BCNU", Desc: "Be seeing you" },
        { Name: "BCOS", Desc: "Because" },
        { Name: "BCO", Desc: "Big crush on" },
        { Name: "BCOY", Desc: "Big crush on you" },
        { Name: "BD", Desc: "Big deal" },
        { Name: "BDAY", Desc: "Birthday" },
        { Name: "B-DAY", Desc: "Birthday" },
        { Name: "BDN", Desc: "Big darn number" },
        { Name: "BEG", Desc: "Big evil grin" },
        { Name: "BELF", Desc: "Meaning 'Blood Elf' (online gaming)" },
        { Name: "BF", Desc: "Boyfriend" },
        { Name: "BF", Desc: "Brain fart" },
        { Name: "BFAW", Desc: "Best friend at work" },
        { Name: "BF2", Desc: "Battlefield 2 (online gaming)" },
        { Name: "BF", Desc: "Best friend" },
        { Name: "BFF", Desc: "Best friends forever" },
        { Name: "BFFL", Desc: "Best friends for life" },
        { Name: "BFFLNMW", Desc: "Best friends for life, no matter what" },
        { Name: "BFD", Desc: "Big freaking deal" },
        { Name: "BFG", Desc: "Big&nbsp; freaking grin" },
        { Name: "BFFN", Desc: "Best friend for now" },
        { Name: "BFN", Desc: "Bye for now" },
        { Name: "BG", Desc: "Big grin" },
        { Name: "BGWM", Desc: "Be gentle with me" },
        { Name: "BHL8", Desc: "Be home late" },
        { Name: "BIB", Desc: "Boss is back" },
        { Name: "BIBO", Desc: "Beer in, beer out" },
        { Name: "BIC", Desc: "Butt in chair" },
        { Name: "BIF", Desc: "Before I forget" },
        { Name: "BIH", Desc: "Burn in hell" },
        { Name: "BIL", Desc: "Brother in law" },
        { Name: "BIO", Desc: "Meaning 'I'm going to the bathroom' (or) 'Bathroom break'" },
        { Name: "BION", Desc: "Believe it or not" },
        { Name: "BIOYA", Desc: "Blow it out your *a*" },
        { Name: "BIOYN", Desc: "Blow it out your nose" },
        { Name: "BIS", Desc: "Best in slot (online gaming)" },
        { Name: "BISFLATM", Desc: "Boy, I sure feel like a turquoise monkey! (unverified)" },
        { Name: "BITMT", Desc: "But in the meantime" },
        { Name: "BL", Desc: "Belly laugh" },
        { Name: "BLNT", Desc: "Better luck next time" },
        { Name: "Bloke", Desc: "Meaning Man (Discord)" },
        { Name: "BM", Desc: "Bite me" },
        { Name: "BME", Desc: "Based on my experience" },
        { Name: "BM&amp;Y", Desc: "Between me and you" },
        { Name: "BOB", Desc: "Back off *buddy*" },
        { Name: "BN", Desc: "Bad news" },
        { Name: "BOE", Desc: "Meaning 'bind on equip' (online gaming)" },
        { Name: "BOHICA", Desc: "Bend over here it comes again" },
        { Name: "BOL", Desc: "Best of luck" },
        { Name: "BOM", Desc: "*b* of mine" },
        { Name: "BOLO", Desc: "Be on the look out" },
        { Name: "BOOMS", Desc: "Bored out of my skull" },
        { Name: "BOP", Desc: "Meaning 'bind on pickup' (online gaming)" },
        { Name: "BOSMKL", Desc: "Bending over smacking my knee laughing" },
        { Name: "BOT", Desc: "Back on topic" },
        { Name: "BOT", Desc: "Be on that" },
        { Name: "BMS", Desc: "Broke my scale, used when rating someone" },
        { Name: "BOYF", Desc: "Boyfriend" },
        { Name: "BPLM", Desc: "Big person little mind" },
        { Name: "BRB", Desc: "Be right back" },
        { Name: "BR", Desc: "Best regards" },
        { Name: "BRBB", Desc: "Be right back *b*" },
        { Name: "BRNC", Desc: "Be right back, nature calls" },
        { Name: "BRD", Desc: "Bored" },
        { Name: "BRH", Desc: "Be right here" },
        { Name: "BRT", Desc: "Be right there" },
        { Name: "BSF", Desc: "But seriously folks" },
        { Name: "BSOD", Desc: "Blue screen of death" },
        { Name: "BSTS", Desc: "Better safe than sorry" },
        { Name: "BT", Desc: "Bite this" },
        { Name: "BT", Desc: "Between technologies" },
        { Name: "BTA", Desc: "But then again" },
        { Name: "BTDT", Desc: "Been there, done that" },
        { Name: "BTW", Desc: "By the way&nbsp;" },
        { Name: "BTYCL", Desc: "Meaning 'Bootycall'" },
        { Name: "BUBU", Desc: "Slang term for the most beautiful of women" },
        { Name: "BURN", Desc: "Used to reference an insult" },
        { Name: "Buff", Desc: "Meaning 'changed and is now stronger' (online gaming)" },
        { Name: "BWL", Desc: "Bursting with laughter&nbsp;" },
        { Name: "BYOB", Desc: "Bring your own beer&nbsp;" },
        { Name: "BYOC", Desc: "Bring your own computer" },
        { Name: "BYOH", Desc: "Bat you on (the) head" },
        { Name: "BYOP", Desc: "Bring your own paint (paintball)" },
        { Name: "BYTM", Desc: "Better you than me" },
        { Name: "C&amp;G", Desc: "Chuckle &amp; grin" },
        { Name: "C4N", Desc: "Ciao for now" },
        { Name: "CAD", Desc: "Control + Alt + Delete" },
        { Name: "CAD", Desc: "Short for Canada/Canadian" },
        { Name: "Cakeday", Desc: "Meaning Birthday (Reddit)" },
        { Name: "CAM", Desc: "Camera (SMS)" },
        { Name: "CB", Desc: "Coffee break" },
        { Name: "CB", Desc: "Chat break" },
        { Name: "CB", Desc: "Crazy *b*" },
        { Name: "CD9", Desc: "Code 9, Meaning 'parents are around'" },
        { Name: "CFS", Desc: "Care for secret?" },
        { Name: "CFY", Desc: "Calling for you" },
        { Name: "CHK", Desc: "Check" },
        { Name: "CIAO", Desc: "Good-bye (Italian word)" },
        { Name: "CICO", Desc: "Coffee in, coffee out" },
        { Name: "CID", Desc: "Crying in disgrace" },
        { Name: "CID", Desc: "Consider it done" },
        { Name: "CLAB", Desc: "Crying like a baby" },
        { Name: "CLD", Desc: "Could" },
        { Name: "CLK", Desc: "Click" },
        { Name: "CM", Desc: "Call me" },
        { Name: "CMAP", Desc: "Cover my *a* partner (online gaming)" },
        { Name: "CMB", Desc: "Call me back" },
        { Name: "CMGR", Desc: "Meaning 'Community manager'" },
        { Name: "CMIIW", Desc: "Correct me if I'm wrong" },
        { Name: "CMON", Desc: "Come on" },
        { Name: "CNP", Desc: "Continued (in) next post" },
        { Name: "COB", Desc: "Close of business" },
        { Name: "COH", Desc: "City of Heroes (online gaming)" },
        { Name: "COS", Desc: "Because" },
        { Name: "C/P", Desc: "Cross post" },
        { Name: "CP", Desc: "Chat post (or continue in IM)" },
        { Name: "CR8", Desc: "Create" },
        { Name: "Cray", Desc: "Meaning crazy" },
        { Name: "CRE8", Desc: "Create" },
        { Name: "CRA CRA", Desc: "Slang term meaning 'crazy'" },
        { Name: "CRAFT", Desc: "Can't remember a *freaking* thing" },
        { Name: "CRB", Desc: "Come right back" },
        { Name: "CRBT", Desc: "Crying really big tears" },
        { Name: "CRIT", Desc: "Meaning 'critical hit' (online gaming)" },
        { Name: "CRZ", Desc: "Crazy" },
        { Name: "CRS&nbsp;", Desc: "Can't remember *stuff*" },
        { Name: "CSG", Desc: "Chuckle, snicker, grin" },
        { Name: "CSL", Desc: "Can't stop laughing" },
        { Name: "CSS", Desc: "Counter-Strike Source (online gaming)" },
        { Name: "CT", Desc: "Can't talk" },
        { Name: "CTC", Desc: "Care to chat?" },
        { Name: "CTHU", Desc: "Cracking the *heck* up" },
        { Name: "CTN", Desc: "Can't talk now" },
        { Name: "CTO", Desc: "Check this out" },
        { Name: "CU", Desc: "See you too" },
        { Name: "CU", Desc: "See you" },
        { Name: "CU2", Desc: "See you" },
        { Name: "CUA", Desc: "See you around" },
        { Name: "CUL", Desc: "See you later" },
        { Name: "CULA", Desc: "See you later alligator" },
        { Name: "CUL8R", Desc: "See you later" },
        { Name: "CUMID", Desc: "See you in my dreams" },
        { Name: "CURLO", Desc: "See you around like a donut" },
        { Name: "CWD", Desc: "Comment when done" },
        { Name: "CWOT", Desc: "Complete waste of time" },
        { Name: "CWYL", Desc: "Chat with you later" },
        { Name: "CX", Desc: "Meaning 'Correction'" },
        { Name: "CYA", Desc: "See you" },
        { Name: "CYAL8R", Desc: "See you later" },
        { Name: "CYE", Desc: "Check your e-mail" },
        { Name: "CYEP", Desc: "Close your eyes partner (online gaming)" },
        { Name: "CYO", Desc: "See you online" },
        { Name: "D2", Desc: "Dedos / fingers (Spanish SMS)" },
        { Name: "D46?", Desc: "Down for sex?" },
        { Name: "DA", Desc: "Meaning 'The'" },
        { Name: "DAE", Desc: "Does anyone else?" },
        { Name: "DAFUQ", Desc: "(What) the *Freak*?" },
        { Name: "DAM", Desc: "Don't annoy me" },
        { Name: "DAoC", Desc: "Dark Age of Camelot (online gaming)" },
        { Name: "DBAU", Desc: "Doing business as usual" },
        { Name: "DBEYR", Desc: "Don't believe everything you read" },
        { Name: "DC", Desc: "Disconnect" },
        { Name: "DD", Desc: "Dear (or Darling) daughter" },
        { Name: "DD", Desc: "Due diligence" },
        { Name: "DDG", Desc: "Drop dead gorgeous" },
        { Name: "DEEZ NUTZ", Desc: "A phrase used in online chat to annoy or frustrate those involved in the conversation." },
        { Name: "DEGT", Desc: "Dear (or Darling) daughter" },
        { Name: "DERP", Desc: "Meaning stupid or silly" },
        { Name: "DF", Desc: "Don't even go there" },
        { Name: "DFL", Desc: "Dead *freaking* last (online gaming)" },
        { Name: "DGA", Desc: "Don't go anywhere" },
        { Name: "DGAF", Desc: "Don't give a *freak*" },
        { Name: "DGT", Desc: "Don't go there" },
        { Name: "DGTG", Desc: "Don't go there, girlfriend" },
        { Name: "DGYF", Desc: "Dang, girl you fine" },
        { Name: "DH", Desc: "Dear (or Darling) husband" },
        { Name: "DHU", Desc: "Dinosaur hugs (used to show support)" },
        { Name: "DIIK", Desc: "Darned if I know" },
        { Name: "DIKU", Desc: "Do I know you?" },
        { Name: "DILLIGAF", Desc: "Do I look like I give a *freak*?" },
        { Name: "DILLIGAS", Desc: "Do I look like I give a sugar?" },
        { Name: "DIS", Desc: "Did I say?" },
        { Name: "DITYID", Desc: "Did I tell you I'm distressed?" },
        { Name: "DIY", Desc: "Do it yourself" },
        { Name: "DKDC", Desc: "Don't know, don't care" },
        { Name: "DKP", Desc: "Dragon kill points (online gaming)" },
        { Name: "D/L", Desc: "Download" },
        { Name: "DL", Desc: "Download" },
        { Name: "DL", Desc: "Down low" },
        { Name: "DL", Desc: "Dead link" },
        { Name: "DLBBB", Desc: "Don't let (the) bed bugs bite" },
        { Name: "DLTBBB", Desc: "Don't let the bed bugs bite" },
        { Name: "DM", Desc: "Doesn't matter" },
        { Name: "DMNO", Desc: "Dude Man No Offense" },
        { Name: "DMY", Desc: "Don't mess yourself" },
        { Name: "DN", Desc: "Down" },
        { Name: "DNC", Desc: "Do not compute (meaning I do not understand)" },
        { Name: "DNR", Desc: "Dinner (SMS)" },
        { Name: "DNT", Desc: "Don't" },
        { Name: "d00d", Desc: "Dude" },
        { Name: "DOE", Desc: "Daughter of Eve" },
        { Name: "DORBS", Desc: "Meaning 'Adorable'" },
        { Name: "DOT", Desc: "Damage over time (online gaming)" },
        { Name: "Downvote", Desc: "Voting negatively on a thread using Reddit’s voting system (Reddit)" },
        { Name: "DPS", Desc: "Damage per second (online gaming)" },
        { Name: "DQMOT", Desc: "Don't quote me on this" },
        { Name: "DR", Desc: "Didn't read" },
        { Name: "DS", Desc: "Dear (or Darling) son" },
        { Name: "DTR", Desc: "Define the relationship" },
        { Name: "DTRT", Desc: "Do the right thing" },
        { Name: "DTS", Desc: "Don't think so" },
        { Name: "DTTD", Desc: "Don't touch that dial" },
        { Name: "DUPE", Desc: "Duplicate" },
        { Name: "DUR", Desc: "Do you remember?" },
        { Name: "DV8", Desc: "Deviate" },
        { Name: "DW", Desc: "Dear (or Darling) wife" },
        { Name: "DWF", Desc: "Divorced white female" },
        { Name: "DWM", Desc: "Divorced white male" },
        { Name: "DXNRY", Desc: "Dictionary" },
        { Name: "DYNWUTB", Desc: "Do you know what you are talking about?" },
        { Name: "DYFI", Desc: "Did you find it?" },
        { Name: "DYFM", Desc: "Dude, you fascinate me" },
        { Name: "DYJHIW", Desc: "Don't you just hate it when...?" },
        { Name: "DYOR", Desc: "Do your own research (common stock market chat slang)" },
        { Name: "E", Desc: "Ecstasy" },
        { Name: "E", Desc: "Enemy (online gaming)" },
        { Name: "E1", Desc: "Everyone" },
        { Name: "E123", Desc: "Easy as one, two, three" },
        { Name: "E2EG", Desc: "Ear to ear grin" },
        { Name: "EAK", Desc: "Eating at keyboard" },
        { Name: "EBKAC", Desc: "Error between keyboard and chair" },
        { Name: "ED", Desc: "Erase display" },
        { Name: "EF4T", Desc: "Effort" },
        { Name: "EG", Desc: "Evil grin" },
        { Name: "EI", Desc: "Eat it" },
        { Name: "EIP", Desc: "Editing in progress" },
        { Name: "ELI5", Desc: "Explain like I'm 5" },
        { Name: "EM", Desc: "E-mail" },
        { Name: "EMA", Desc: "E-mail address" },
        { Name: "EMBAR", Desc: "Meaning 'Embarassing'" },
        { Name: "EMFBI", Desc: "Excuse me for butting in" },
        { Name: "EMFBI", Desc: "Excuse me for jumping in" },
        { Name: "EMSG", Desc: "E-mail message" },
        { Name: "ENUF", Desc: "Enough" },
        { Name: "EOD", Desc: "End of day" },
        { Name: "EOD", Desc: "End of discussion" },
        { Name: "EOL", Desc: "End of lecture" },
        { Name: "EOL", Desc: "End of life" },
        { Name: "EOM", Desc: "End of message" },
        { Name: "EOS", Desc: "End of show" },
        { Name: "EOT", Desc: "End of transmission" },
        { Name: "EQ", Desc: "EverQuest (online gaming)" },
        { Name: "ERP", Desc: "Meaning 'Erotic Role-Play' (online gaming)" },
        { Name: "ERS2", Desc: "Eres tz / are you (Spanish SMS)" },
        { Name: "ES", Desc: "Erase screen" },
        { Name: "ESAD", Desc: "Eat *S* and die!" },
        { Name: "ETA", Desc: "Estimated time (of) arrival" },
        { Name: "ETA", Desc: "Edited to add" },
        { Name: "EVA", Desc: "Ever" },
        { Name: "EVO", Desc: "Evolution" },
        { Name: "EWG", Desc: "Evil wicked grin (in fun, teasing)" },
        { Name: "EWI", Desc: "Emailing while intoxicated" },
        { Name: "EXTRA", Desc: "Meaning over the top" },
        { Name: "EYC", Desc: "Excitable, yet calm" },
        { Name: "EZ", Desc: "Easy" },
        { Name: "EZY", Desc: "Easy" },
        { Name: "F", Desc: "Meaning female" },
        { Name: "F2F", Desc: "Face to face" },
        { Name: "F2P", Desc: "Free to play (online gaming)" },
        { Name: "F4F", Desc: "Follow for follow (Instagram)" },
        { Name: "FAAK", Desc: "Falling asleep at keyboard" },
        { Name: "FAB", Desc: "Fabulous" },
        { Name: "Facepalm", Desc: "Used to represent the gesture of 'smacking your forehead with your palm' to express embarrassment or frustration" },
        { Name: "FAF", Desc: "Funny as *freak*" },
        { Name: "FAM", Desc: "FFamily, but not limited to actual family members. Could mean friends." },
        { Name: "FAQ", Desc: "Frequently asked questions" },
        { Name: "FAY", Desc: "*Freak* all you" },
        { Name: "FB", Desc: "Facebook" },
        { Name: "FBB", Desc: "Meaning 'Facebook buddy'" },
        { Name: "FBC", Desc: "Facebook chat" },
        { Name: "FBF", Desc: "Flashback Friday" },
        { Name: "FBF", Desc: "Meaning 'Facebook friend'" },
        { Name: "FBF", Desc: "Fat boy food (e.g. pizza, burgers, fries)" },
        { Name: "FBFR", Desc: "FaceBook friend" },
        { Name: "FBM", Desc: "Fine by me" },
        { Name: "FBO", Desc: "Facebook official (An official update from Facebook)" },
        { Name: "FBOW", Desc: "For better or worse" },
        { Name: "FC", Desc: "Fingers crossed" },
        { Name: "FC", Desc: "Full card (online gaming)" },
        { Name: "FC'INGO", Desc: "For crying out loud" },
        { Name: "FCOL", Desc: "For crying out loud" },
        { Name: "Feelsbadman", Desc: "A social meme that means to feel negative." },
        { Name: "Feelsbatman", Desc: "A social meme taking 'feelsbadman' to the extreme. This references the DC super hero Batmanbecause he witnessed the murder of his parents." },
        { Name: "Feelsgoodman", Desc: "A social meme that means to feel positive." },
        { Name: "FEITCTAJ", Desc: "*Freak* 'em if they can't take a joke" },
        { Name: "FF", Desc: "Follow Friday" },
        { Name: "FFA", Desc: "Free for all (online gaming)" },
        { Name: "FFS", Desc: "For *freak'*sakes" },
        { Name: "FICCL", Desc: "Frankly I couldn't care a less" },
        { Name: "FIF", Desc: "*Freak* I'm funny" },
        { Name: "FIIK", Desc: "*Freaked* if I know" },
        { Name: "FIIOOH", Desc: "Forget it, I'm out of here" },
        { Name: "FIL", Desc: "Father in law" },
        { Name: "FIMH", Desc: "Forever in my heart" },
        { Name: "Finna", Desc: "Means 'Going to'" },
        { Name: "Finsta", Desc: "A second Instagram account where someone can post things that they're too afraid to post on their main account." },
        { Name: "FISH", Desc: "First in, still here" },
        { Name: "FITB", Desc: "Fill in the blank" },
        { Name: "FML", Desc: "*Freak* My Life" },
        { Name: "FOMC", Desc: "Falling off my chair" },
        { Name: "FOMO", Desc: "Fear of missing out" },
        { Name: "FOAD", Desc: "*Freak* off and die" },
        { Name: "FOAF", Desc: "Friend of a friend" },
        { Name: "FOMCL", Desc: "Falling off my chair laughing" },
        { Name: "FRT", Desc: "For real though" },
        { Name: "FTBOMH", Desc: "From the bottom of my heart" },
        { Name: "FTFY", Desc: "Fixed that for you" },
        { Name: "FTL", Desc: "For the loss" },
        { Name: "FTW", Desc: "For the win" },
        { Name: "FU", Desc: "*Freak* you" },
        { Name: "FUBAR", Desc: "Fouled up beyond all recognition" },
        { Name: "FUBB", Desc: "Fouled up beyond belief" },
        { Name: "FUD", Desc: "Face up deal (online gaming)" },
        { Name: "FUTAB", Desc: "Feet up, take a break" },
        { Name: "FW", Desc: "Forward" },
        { Name: "FWB", Desc: "Friend with benefits" },
        { Name: "FWIW", Desc: "For what it's worth" },
        { Name: "FWM", Desc: "Fine with me" },
        { Name: "FWP", Desc: "First world problems" },
        { Name: "FYE", Desc: "Fire, something that is cool" },
        { Name: "FYEO", Desc: "For your eyes only" },
        { Name: "FYA", Desc: "For your amusement" },
        { Name: "FYI", Desc: "For your information" },
        { Name: "G", Desc: "Grin" },
        { Name: "G", Desc: "Giggle" },
        { Name: "G+", Desc: "Google+" },
        { Name: "G/F", Desc: "Girlfriend" },
        { Name: "G2CU", Desc: "Good to see you" },
        { Name: "G2G", Desc: "Got to go" },
        { Name: "G2GICYAL8ER", Desc: "Got to go I'll see you later" },
        { Name: "G2R", Desc: "Got to run" },
        { Name: "G2TU", Desc: "Got to tell u (you)" },
        { Name: "G4C", Desc: "Going for coffee" },
        { Name: "G9", Desc: "Genius" },
        { Name: "GA", Desc: "Go ahead" },
        { Name: "GAC", Desc: "Get a clue" },
        { Name: "GAFC", Desc: "Get a *freaking* clue" },
        { Name: "GAL", Desc: "Get a life" },
        { Name: "GANK", Desc: "Meaning a player ambush or unfair player kill (online gaming)" },
        { Name: "GAS", Desc: "Got a second?" },
        { Name: "GAS", Desc: "Greetings and salutations" },
        { Name: "GB", Desc: "Goodbye" },
        { Name: "GBTW", Desc: "Get back to work" },
        { Name: "GBU", Desc: "God bless you" },
        { Name: "GD", Desc: "Good" },
        { Name: "GDR", Desc: "Grinning, ducking, and running" },
        { Name: "GD/R", Desc: "Grinning, ducking, and running" },
        { Name: "GFI", Desc: "Go for it" },
        { Name: "GF", Desc: "Girl friend" },
        { Name: "GFN", Desc: "Gone for now" },
        { Name: "GG", Desc: "Gotta Go" },
        { Name: "GG", Desc: "Good Game (online gaming)" },
        { Name: "GG", Desc: "Brother (Mandarin Chinese txt msgs)" },
        { Name: "GGA", Desc: "Good game, all (online gaming)" },
        { Name: "GGE1", Desc: "Good game, everyone (online gaming)" },
        { Name: "GGU2", Desc: "Good game, you too" },
        { Name: "GGMSOT", Desc: "Gotta get me some of that" },
        { Name: "GGOH", Desc: "Gotta Get Outa Here" },
        { Name: "GGP", Desc: "Got to go pee" },
        { Name: "GH", Desc: "Good hand (online gaming)" },
        { Name: "GIAR", Desc: "Give it a rest" },
        { Name: "GIC", Desc: "Gift in crib (online gaming)" },
        { Name: "GIGO", Desc: "Garbage in, garbage out" },
        { Name: "GIRL", Desc: "Guy in real life" },
        { Name: "GJ", Desc: "Good job" },
        { Name: "GL", Desc: "Good luck" },
        { Name: "GL2U", Desc: "Good luck to you (online gaming)" },
        { Name: "GLA", Desc: "Good luck all (online gaming)" },
        { Name: "GL/HF", Desc: "Good luck, have fun&nbsp; (online gaming)" },
        { Name: "GLE", Desc: "Good luck everyone (online gaming)" },
        { Name: "GLE1", Desc: "Good luck everyone (online gaming)" },
        { Name: "GLNG", Desc: "Good luck next game (online gaming)" },
        { Name: "GMBA", Desc: "Giggling my butt off" },
        { Name: "GMTA", Desc: "Great minds think alike" },
        { Name: "GMV", Desc: "Got my vote" },
        { Name: "GN", Desc: "Good night" },
        { Name: "GNA", Desc: "Good night all" },
        { Name: "GNE1", Desc: "Good night everyone" },
        { Name: "GNIGHT", Desc: "Good night" },
        { Name: "GNITE", Desc: "Good night" },
        { Name: "GNSD", Desc: "Good night, sweet dreams" },
        { Name: "GOAT", Desc: "Greatest of all Time(s)" },
        { Name: "GOI", Desc: "Get over it" },
        { Name: "GOL", Desc: "Giggling out loud" },
        { Name: "GOMB", Desc: "Get off my back" },
        { Name: "GPOY", Desc: "Gratuitous picture of yourself" },
        { Name: "GR8", Desc: "Great" },
        { Name: "GRATZ", Desc: "Congratulations" },
        { Name: "GRL", Desc: "Girl" },
        { Name: "GRWG", Desc: "Get right with God" },
        { Name: "GR&amp;D", Desc: "Grinning, running and ducking" },
        { Name: "GS", Desc: "Good shot" },
        { Name: "GS", Desc: "Good split (online gaming)" },
        { Name: "GT", Desc: "Good try" },
        { Name: "GTFO", Desc: "Get the *freak* out" },
        { Name: "GTFOH", Desc: "Get the *freak* outta here" },
        { Name: "GTG", Desc: "Got to go" },
        { Name: "GTM", Desc: "Giggling to myself" },
        { Name: "GTRM", Desc: "Going to read mail&nbsp;" },
        { Name: "GTSY", Desc: "Great (or good) to see you" },
        { Name: "GUCCI", Desc: "Good" },
        { Name: "GUD", Desc: "Good&nbsp;" },
        { Name: "GWHTLC", Desc: "Glad we had this little chat" },
        { Name: "H", Desc: "Hug" },
        { Name: "H8", Desc: "Hate" },
        { Name: "H8TTU", Desc: "Hate to be you" },
        { Name: "HAG1", Desc: "Have a good one" },
        { Name: "HAK", Desc: "Hug and kiss" },
        { Name: "HALP", Desc: "Help (Discord)" },
        { Name: "HAU", Desc: "How about you?" },
        { Name: "H&amp;K", Desc: "Hugs &amp; kisses" },
        { Name: "H2CUS", Desc: "Hope to see you soon" },
        { Name: "HAGN", Desc: "Have a good night" },
        { Name: "HAGO", Desc: "Have a good one" },
        { Name: "HAND", Desc: "Have a nice day" },
        { Name: "HAWT", Desc: "Have a wonderful day (out-dated, see next in list)" },
        { Name: "HAWT", Desc: "Meaning 'sexy' or 'attractive'" },
        { Name: "HB", Desc: "Hurry back" },
        { Name: "HB", Desc: "Hug back" },
        { Name: "HBD", Desc: "Happy birthday" },
        { Name: "H-BDAY", Desc: "Happy Birthday" },
        { Name: "HBU", Desc: "How about you?" },
        { Name: "HF", Desc: "Have fun" },
        { Name: "HFAC", Desc: "Holy flipping animal crackers" },
        { Name: "H-FDAY", Desc: "Happy Father's Day" },
        { Name: "HHIS", Desc: "Head hanging in shame" },
        { Name: "HIFW", Desc: "How I felt when... (Used with photo or gif)" },
        { Name: "HL", Desc: "Half Life (online gaming)" },
        { Name: "HLA", Desc: "Hola / hello (Spanish SMS)" },
        { Name: "H-MDAY", Desc: "Happy Mother's Day" },
        { Name: "HMU", Desc: "Hit me up" },
        { Name: "HNL", Desc: "(w)Hole 'nother level" },
        { Name: "HOAS", Desc: "Hold on a second" },
        { Name: "HP", Desc: "Hit points / Health points (online gaming)" },
        { Name: "HRU", Desc: "How are you?" },
        { Name: "HTH", Desc: "Hope this helps" },
        { Name: "HUB", Desc: "Head up butt" },
        { Name: "HUYA", Desc: "Head up your *butt*" },
        { Name: "HV", Desc: "Have&nbsp;" },
        { Name: "HVH", Desc: "Heroic Violet Hold (online gaming)" },
        { Name: "HW", Desc: "Homework" },
        { Name: "HYFR", Desc: "Hell yeah, *Freaking* right!" },
        { Name: "I2", Desc: "I too (me too)" },
        { Name: "IA8", Desc: "I already ate" },
        { Name: "IAAA", Desc: "I am an accountant" },
        { Name: "IAAD", Desc: "I am a doctor" },
        { Name: "IAAL", Desc: "I am a lawyer" },
        { Name: "IAC", Desc: "In any case" },
        { Name: "IAE", Desc: "In any event" },
        { Name: "IANAC", Desc: "I am not a crook" },
        { Name: "IANAL", Desc: "I am not a lawyer" },
        { Name: "IAO", Desc: "I am out (of here)" },
        { Name: "IB", Desc: "I'm back" },
        { Name: "IB", Desc: "I'm back" },
        { Name: "IC", Desc: "I see" },
        { Name: "ICAM", Desc: "I couldn't agree more" },
        { Name: "ICBW", Desc: "It could be worse" },
        { Name: "ICEDI", Desc: "I can't even discuss it" },
        { Name: "ICFILWU", Desc: "I could fall in love with you" },
        { Name: "ICYMI", Desc: "In case you missed it (Twitter slang)" },
        { Name: "IDBI", Desc: "I don't believe it" },
        { Name: "IDC", Desc: "I don't care" },
        { Name: "IDGAF", Desc: "&nbsp;I don't give a *freak*" },
        { Name: "IDK", Desc: "I don't know" },
        { Name: "IDTS", Desc: "I don't think so" },
        { Name: "IDUNNO", Desc: "I don't know" },
        { Name: "IFYP", Desc: "I feel your pain" },
        { Name: "IG", Desc: "Instagram" },
        { Name: "IG2R", Desc: "I got to run" },
        { Name: "IGHT", Desc: "I got high tonight" },
        { Name: "IGN", Desc: "I (I've) got nothing" },
        { Name: "IGP", Desc: "I got to (go) pee" },
        { Name: "IHNI", Desc: "I have no idea" },
        { Name: "IIRC", Desc: "If I remember correctly" },
        { Name: "IIIO", Desc: "Intel inside, idiot outside" },
        { Name: "IK", Desc: "I know" },
        { Name: "IKR", Desc: "I know, right?" },
        { Name: "ILBL8", Desc: "I'll be late" },
        { Name: "ILU", Desc: "I love you" },
        { Name: "ILUM", Desc: "I love you man" },
        { Name: "ILYSM", Desc: "I love you so much" },
        { Name: "ILY", Desc: "I love you" },
        { Name: "IM", Desc: "Instant message" },
        { Name: "IMAO", Desc: "In my arrogant opinion" },
        { Name: "IMHO", Desc: "In my humble opinion" },
        { Name: "ImL", Desc: "(in Arial font) Means I love you (a way of using the American sign language in text)" },
        { Name: "IMNSHO", Desc: "In my not so humble opinion" },
        { Name: "IMO", Desc: "In my opinion" },
        { Name: "IMS", Desc: "I am sorry" },
        { Name: "IMSB", Desc: "I am so bored" },
        { Name: "IMTM", Desc: "I am the man" },
        { Name: "IMU", Desc: "I miss u (you)" },
        { Name: "INAL", Desc: "I'm not a lawyer" },
        { Name: "INC", Desc: "Meaning 'incoming' (online gaming)" },
        { Name: "Inspoo", Desc: "Inspiration" },
        { Name: "INV", Desc: "Meaning 'Invite'" },
        { Name: "IOMH", Desc: "In over my head" },
        { Name: "IOW", Desc: "In other words" },
        { Name: "IRL", Desc: "In real life" },
        { Name: "IRMC", Desc: "I rest my case" },
        { Name: "ISLY", Desc: "I still love you" },
        { Name: "ISO", Desc: "In search of" },
        { Name: "ITAM", Desc: "It's The Accounting, Man (financial blogs)" },
        { Name: "ITT", Desc: "In This Thread" },
        { Name: "ITYK", Desc: "I thought you knew" },
        { Name: "IUSS", Desc: "If you say so" },
        { Name: "IWALU", Desc: "I will always love you" },
        { Name: "IWAWO", Desc: "I want a way out" },
        { Name: "IWIAM", Desc: "Idiot wrapped in a moron" },
        { Name: "IWSN", Desc: "I want sex now" },
        { Name: "IYKWIM", Desc: "If you know what I mean" },
        { Name: "IYO", Desc: "In your opinion" },
        { Name: "IYQ", Desc: "Meaning 'I like you'" },
        { Name: "IYSS", Desc: "If you say so" },
        { Name: "j00", Desc: "You" },
        { Name: "j00r", Desc: "Your" },
        { Name: "JAC", Desc: "Just a second" },
        { Name: "JAM", Desc: "Just a minute" },
        { Name: "JAS", Desc: "Just a second" },
        { Name: "JC (J/C)", Desc: "Just checking" },
        { Name: "JDI", Desc: "Just do it" },
        { Name: "JELLY", Desc: "Meaning 'jealous'" },
        { Name: "JFF", Desc: "Just for fun" },
        { Name: "JFGI", Desc: "Just *freaking* Google it" },
        { Name: "JIC", Desc: "Just in case" },
        { Name: "JJ (J/J)", Desc: "Just joking" },
        { Name: "JJA", Desc: "Just joking around" },
        { Name: "JK (J/K)", Desc: "Just kidding" },
        { Name: "JLMK", Desc: "Just let me know" },
        { Name: "JMO", Desc: "Just my opinion" },
        { Name: "JP", Desc: "Just playing&nbsp;" },
        { Name: "JP", Desc: "Jackpot (online gaming, bingo games)" },
        { Name: "JT (J/T)", Desc: "Just teasing" },
        { Name: "JTLYK", Desc: "Just to let you know" },
        { Name: "JV", Desc: "Joint venture" },
        { Name: "JW", Desc: "Just wondering" },
        { Name: "K", Desc: "Okay" },
        { Name: "KK", Desc: "Knock, knock" },
        { Name: "KK", Desc: "Okay, Okay!" },
        { Name: "K8T", Desc: "Katie" },
        { Name: "k/b", Desc: "Keyboard" },
        { Name: "KB", Desc: "Keyboard" },
        { Name: "KB", Desc: "Kick butt (online gaming)" },
        { Name: "KDFU", Desc: "Means Cracking (K) the (D as in Da) *freak* up" },
        { Name: "KEWL", Desc: "Cool" },
        { Name: "KEYA", Desc: "I will key you later" },
        { Name: "KEYME", Desc: "Key me when you get in" },
        { Name: "KFY", Desc: "Kiss for you" },
        { Name: "KIA", Desc: "Know it all" },
        { Name: "KIR", Desc: "Keep it real" },
        { Name: "KISS", Desc: "Keep it simple, stupid" },
        { Name: "KIT", Desc: "Keep in touch" },
        { Name: "KMA", Desc: "Kiss my *a*" },
        { Name: "KMK", Desc: "Kiss my keister" },
        { Name: "KMS", Desc: "Killing myself" },
        { Name: "KMT", Desc: "Kiss my tushie" },
        { Name: "KOC", Desc: "Kiss on cheek" },
        { Name: "KOL", Desc: "Key opinion leader" },
        { Name: "Koreaboo", Desc: "Someone obsessed with Korean culture" },
        { Name: "KOS", Desc: "Kid over shoulder" },
        { Name: "KOS", Desc: "Kill on sight (online gaming)" },
        { Name: "KOW", Desc: "Knock on wood" },
        { Name: "KOTC", Desc: "Kiss on the cheek" },
        { Name: "KOTD", Desc: "Kicks of the day (Instagram)" },
        { Name: "KOTL", Desc: "Kiss on the lips" },
        { Name: "KNIM", Desc: "Know what I mean?" },
        { Name: "KNOW", Desc: "Meaning 'knowledge'" },
        { Name: "KPC", Desc: "Keeping parents clueless" },
        { Name: "KS", Desc: "Kill then steal (online gaming)" },
        { Name: "KSC", Desc: "Kind (of) sort (of) chuckle" },
        { Name: "KT", Desc: "Katie" },
        { Name: "KUTGW", Desc: "Keep up the good work" },
        { Name: "KYS", Desc: "Kill yourself" },
        { Name: "L2G", Desc: "Like to go?" },
        { Name: "L2G", Desc: "(would) Love to go" },
        { Name: "L2K", Desc: "Like to come" },
        { Name: "L2P", Desc: "Learn to play" },
        { Name: "l33t", Desc: "Leet, meaning 'elite'" },
        { Name: "L4L", Desc: "Like for like (Instagram)" },
        { Name: "L8R", Desc: "Later" },
        { Name: "L8RG8R", Desc: "Later, gator" },
        { Name: "LAB", Desc: "Life's a *b*" },
        { Name: "LBAY", Desc: "Laughing back at you" },
        { Name: "LBS", Desc: "Laughing, but serious" },
        { Name: "LBVS", Desc: "Laughing, but very serious" },
        { Name: "LD", Desc: "Later, dude" },
        { Name: "LD", Desc: "Long distance" },
        { Name: "LDO", Desc: "Like, duh obviously" },
        { Name: "LEMENO", Desc: "Let me know" },
        { Name: "LERK", Desc: "Leaving easy reach of keyboard" },
        { Name: "LFD", Desc: "Left for day" },
        { Name: "LFG", Desc: "Looking for group (online gaming)" },
        { Name: "LFG", Desc: "Looking for guard (online gaming)" },
        { Name: "LFM", Desc: "Looking for more (online gaming)" },
        { Name: "LGH", Desc: "Lets get high" },
        { Name: "LH6", Desc: "Lets have sex" },
        { Name: "LHSX", Desc: "Lets have sex" },
        { Name: "LHM", Desc: "Lord help me" },
        { Name: "LHO", Desc: "Laughing head off" },
        { Name: "LI", Desc: "LinkedIn" },
        { Name: "LIC", Desc: "Like I care" },
        { Name: "LIK", Desc: "Meaning liquor" },
        { Name: "LIMT", Desc: "Laugh in my tummy" },
        { Name: "LIT", Desc: "Meaning really good or something fun and exciting" },
        { Name: "LIT", Desc: "Extremely intoxicated" },
        { Name: "LLGB", Desc: "Love, later, God bless" },
        { Name: "LLS", Desc: "Laughing like *silly*" },
        { Name: "LMAO", Desc: "Laughing my *a* off" },
        { Name: "LMBO", Desc: "Laughing my butt off" },
        { Name: "LMFAO", Desc: "Laughing my freaking *a* off" },
        { Name: "LMIRL", Desc: "Lets meet in real life" },
        { Name: "LMK", Desc: "Let me know" },
        { Name: "LMMFAO", Desc: "Laughing my mother freaking a** off" },
        { Name: "LMNK", Desc: "Leave my name out" },
        { Name: "LMS", Desc: "Like my status (Facebook)" },
        { Name: "LNT", Desc: "Meaning lost in translation" },
        { Name: "LOA", Desc: "List of acronyms" },
        { Name: "LOL", Desc: "Laughing out loud" },
        { Name: "LOLH", Desc: "Laughing out loud hysterically" },
        { Name: "LOLO", Desc: "Lots of love" },
        { Name: "LOLWTF", Desc: "Laughing out loud (saying) 'What the *freak*?'" },
        { Name: "LOTI", Desc: "Laughing on the inside" },
        { Name: "LOTR", Desc: "Lord of The Rings (online gaming)" },
        { Name: "LQTM", Desc: "Laughing quietly to myself" },
        { Name: "LSHMBH", Desc: "Laugh so hard my belly hurts" },
        { Name: "LSV", Desc: "Language, sex and violence" },
        { Name: "LTD", Desc: "Living the dream" },
        { Name: "LTLWDLS", Desc: "Let's twist like we did last summer" },
        { Name: "LTNS", Desc: "Long time no see" },
        { Name: "LTOD", Desc: "Laptop of death" },
        { Name: "LTS", Desc: "Laughing to self" },
        { Name: "LULT", Desc: "Love you long time" },
        { Name: "LULZ", Desc: "Meaning joke, or for laughs" },
        { Name: "LVM", Desc: "Left voice mail" },
        { Name: "LWOS", Desc: "Laughing without smiling" },
        { Name: "LY", Desc: "Love ya&nbsp;" },
        { Name: "LYLAS", Desc: "Love you like a sis" },
        { Name: "LYLC", Desc: "Love you like crazy" },
        { Name: "LYSM", Desc: "Love you so much" },
        { Name: "M$", Desc: "Microsoft" },
        { Name: "M8", Desc: "Mate" },
        { Name: "MB", Desc: "Mamma's boy" },
        { Name: "MBS", Desc: "Mom behind shoulder" },
        { Name: "MC", Desc: "Merry Christmas" },
        { Name: "MDIAC", Desc: "My Dad is a cop" },
        { Name: "MEGO", Desc: "My eyes glaze over" },
        { Name: "MEH", Desc: "Meaning a 'shrug' or shrugging shoulders" },
        { Name: "MEH", Desc: "Meaning a 'so-so' or 'just okay'" },
        { Name: "MEHH", Desc: "Meaning a 'sigh' or sighing" },
        { Name: "MEZ", Desc: "Meaning 'mesmerize' (online gaming)" },
        { Name: "MFI", Desc: "Mad for it" },
        { Name: "MFW", Desc: "My face when... (Used with photo or gif)" },
        { Name: "MGB", Desc: "May God bless" },
        { Name: "MGMT", Desc: "Management" },
        { Name: "MHOTY", Desc: "My hat (is) off to you" },
        { Name: "MIRL", Desc: "Me in real life" },
        { Name: "MIRL", Desc: "Meet in real life" },
        { Name: "MISS.(number)", Desc: "Meaning 'child and her age'. Miss.3 would be a 3-year old daughter" },
        { Name: "MKAY", Desc: "Meaning 'Mmm, okay'" },
        { Name: "MLM", Desc: "Meaning give the middle finger" },
        { Name: "MM", Desc: "Sister (Mandarin Chinese txt msg)" },
        { Name: "MMK", Desc: "Meaning okay? (as a question)" },
        { Name: "MNC", Desc: "Mother nature calls" },
        { Name: "MNSG", Desc: "Mensaje (message in Spanish)" },
        { Name: "MOD", Desc: "Moderator" },
        { Name: "MOD", Desc: "Modification (online gaming)" },
        { Name: "MORF", Desc: "Male or female?" },
        { Name: "MOMBOY", Desc: "Mamma's boy" },
        { Name: "MOO", Desc: "My own opinion" },
        { Name: "MOOS", Desc: "Member of the opposite sex" },
        { Name: "MOS", Desc: "Mother over shoulder" },
        { Name: "MOSS", Desc: "Member of same sex" },
        { Name: "MP", Desc: "Mana points (online gaming)" },
        { Name: "MR.(number)", Desc: "Meaning 'child and his age'. Mr.3 would be a 3-year old son" },
        { Name: "MRT", Desc: "Modified ReTweet" },
        { Name: "MRW", Desc: "My reaction when... (Used with photo or gif)" },
        { Name: "MSG", Desc: "Message" },
        { Name: "MTF", Desc: "More to follow" },
        { Name: "MTFBWU", Desc: "May the force be with you" },
        { Name: "MU", Desc: "Miss U (you)" },
        { Name: "MUAH", Desc: "Multiple unsuccessful attempts (at/to) humor" },
        { Name: "MUSM", Desc: "Miss you so much" },
        { Name: "MWAH", Desc: "Meaning 'kiss' (it is is the sound made when kissing through the air)" },
        { Name: "MYO", Desc: "Mind your own (business)" },
        { Name: "MYOB", Desc: "Mind your own business" },
        { Name: "n00b", Desc: "Newbie" },
        { Name: "N1", Desc: "Nice one" },
        { Name: "N2M", Desc: "Nothing too much" },
        { Name: "NADT", Desc: "Not a darn thing" },
        { Name: "NALOPKT", Desc: "Not a lot of people know that" },
        { Name: "NANA", Desc: "Not now, no need" },
        { Name: "NBD", Desc: "No big deal" },
        { Name: "NBFAB", Desc: "No bad for a beginner (online gaming)" },
        { Name: "NC", Desc: "Nice crib (online gaming)" },
        { Name: "ND", Desc: "Nice double (online gaming)" },
        { Name: "NE", Desc: "Any" },
        { Name: "NE1", Desc: "Anyone" },
        { Name: "NERF", Desc: "Meaning 'Changed and is now weaker' (online gaming)" },
        { Name: "NFM", Desc: "None for me / Not for me" },
        { Name: "NFM", Desc: "Not for me" },
        { Name: "NGL", Desc: "Not gonna (going to) lie" },
        { Name: "NFS", Desc: "Need for Speed (online gaming)" },
        { Name: "NFS", Desc: "Not for sale" },
        { Name: "NFW", Desc: "No *freaking* way" },
        { Name: "NFW", Desc: "Not for work" },
        { Name: "NFWS", Desc: "Not for work safe" },
        { Name: "NH", Desc: "Nice hand (online gaming)" },
        { Name: "NIFOC", Desc: "Naked in front of computer" },
        { Name: "NIGI", Desc: "Now I get it" },
        { Name: "NIMBY", Desc: "Not in my back yard" },
        { Name: "NIROK", Desc: "Not in reach of keyboard" },
        { Name: "NLT", Desc: "No later than" },
        { Name: "NM", Desc: "Nothing much" },
        { Name: "NM", Desc: "Never mind" },
        { Name: "NM", Desc: "Nice meld (online gaming)" },
        { Name: "NMH", Desc: "Not much here" },
        { Name: "NMJC", Desc: "Nothing much, just chilling" },
        { Name: "NMU", Desc: "Not much, you?" },
        { Name: "NO1", Desc: "No one" },
        { Name: "NOOB", Desc: "Meaning someone who is bad at (online) games" },
        { Name: "NOWL", Desc: "Meaning 'knowledge'" },
        { Name: "NOYB", Desc: "None of your business" },
        { Name: "NP", Desc: "No problem" },
        { Name: "NPC", Desc: "Non-playing character (online gaming)" },
        { Name: "NQT", Desc: "Newly qualified teacher" },
        { Name: "NR", Desc: "Nice roll (online gaming)" },
        { Name: "NRN", Desc: "No response/reply necessary" },
        { Name: "NS", Desc: "Nice score (online gaming)" },
        { Name: "NS", Desc: "Nice split (online gaming)" },
        { Name: "NSA", Desc: "No strings attached" },
        { Name: "NSFL", Desc: "Not safe for life" },
        { Name: "NSFW", Desc: "Not safe for work" },
        { Name: "NSISR", Desc: "Not sure if spelled right" },
        { Name: "NT", Desc: "Nice try" },
        { Name: "NTHING", Desc: "Nothing (SMS)" },
        { Name: "NTS", Desc: "Note to self" },
        { Name: "NVM", Desc: "Never mind" },
        { Name: "NVR", Desc: "Never" },
        { Name: "NW", Desc: "No way" },
        { Name: "NWO", Desc: "No way out" },
        { Name: "O4U", Desc: "Only for you" },
        { Name: "O", Desc: "Opponent (online gaming)" },
        { Name: "O", Desc: "Meaning 'hugs'" },
        { Name: "O", Desc: "Over" },
        { Name: "OA", Desc: "Online auctions" },
        { Name: "OATUS", Desc: "On a totally unrelated subject" },
        { Name: "OB", Desc: "Oh baby" },
        { Name: "OB", Desc: "Oh brother" },
        { Name: "OBV", Desc: "Obviously" },
        { Name: "OFC", Desc: "Of course" },
        { Name: "OG", Desc: "Original gangster" },
        { Name: "OGIM", Desc: "Oh God, it's Monday" },
        { Name: "OH", Desc: "Overheard" },
        { Name: "OHHEMMGEE", Desc: "Meaning 'Oh My God' (alternate of OMG)" },
        { Name: "OI", Desc: "Operator indisposed" },
        { Name: "OIB", Desc: "Oh, I'm back" },
        { Name: "OIC", Desc: "Oh, I see" },
        { Name: "OJ", Desc: "Only joking" },
        { Name: "OL", Desc: "Old lady" },
        { Name: "OLL", Desc: "Online love" },
        { Name: "OM", Desc: "Old man" },
        { Name: "OM", Desc: "Oh, my" },
        { Name: "OMAA", Desc: "Oh, my aching *A* (butt)" },
        { Name: "OMDB", Desc: "Over my dead body" },
        { Name: "OMFG", Desc: "Oh my *freaking* God" },
        { Name: "omfglmaobbqrofl", Desc: "oh my *freaking* god, laugh my *a* off, owned, roll on floor spinning around I'm so sad" },
        { Name: "OMG", Desc: "Oh my God" },
        { Name: "OMG", Desc: "Oh my gosh" },
        { Name: "OMGYG2BK", Desc: "Oh my God, you got to be kidding" },
        { Name: "OMGYS", Desc: "Oh my gosh you suck&nbsp;" },
        { Name: "OMS", Desc: "On my soul (meaning 'promise')" },
        { Name: "OMW", Desc: "On my way" },
        { Name: "ONL", Desc: "Online" },
        { Name: "OO", Desc: "Over and out" },
        { Name: "OOC", Desc: "Out of character" },
        { Name: "OOH", Desc: "Out of here" },
        { Name: "OOMF", Desc: "One of my followers" },
        { Name: "OOTD", Desc: "One of these days" },
        { Name: "OOTD", Desc: "Outfit of the day (Instagram)" },
        { Name: "OOTO", Desc: "Out of the office" },
        { Name: "OP", Desc: "On phone" },
        { Name: "ORLY", Desc: "Oh really?" },
        { Name: "OS", Desc: "Operating system" },
        { Name: "OT", Desc: "Off topic (discussion forums)" },
        { Name: "OTB", Desc: "Off to bed" },
        { Name: "OTFL", Desc: "On the floor laughing" },
        { Name: "OTL", Desc: "Out to lunch" },
        { Name: "OTOH", Desc: "On the other hand" },
        { Name: "OTP", Desc: "On the phone" },
        { Name: "OTP", Desc: "One true pairing; two people you would love to see as a couple" },
        { Name: "OTT", Desc: "Over the top" },
        { Name: "OTTOMH", Desc: "Off the top of my head" },
        { Name: "OTW", Desc: "Off to work" },
        { Name: "OVA", Desc: "Over" },
        { Name: "OYO", Desc: "On your own" },
        { Name: "P", Desc: "Partner (online gaming)" },
        { Name: "P2P", Desc: "Parent to parent" },
        { Name: "P2P", Desc: "Peer to peer" },
        { Name: "P2P", Desc: "Pay to play (online gaming)" },
        { Name: "P911", Desc: "Parents coming into room alert" },
        { Name: "PAP", Desc: "Post a picture" },
        { Name: "PAT", Desc: "Meaning 'patrol' (online gaming)" },
        { Name: "PAW", Desc: "Parents are watching" },
        { Name: "PBOOK", Desc: "Phonebook (e-mail)" },
        { Name: "PC", Desc: "Player character (online gaming)" },
        { Name: "PCM", Desc: "Please call me" },
        { Name: "PDA", Desc: "Personal display (of) affection" },
        { Name: "PDH", Desc: "Pretty darn happy" },
        { Name: "PDS", Desc: "Please don't shoot" },
        { Name: "PDQ", Desc: "Pretty darn quick" },
        { Name: "PEEPS", Desc: "People" },
        { Name: "PFT", Desc: "Pretty *freaking* tight" },
        { Name: "PIC", Desc: "Picture" },
        { Name: "PIP", Desc: "Peeing in pants (laughing hard)" },
        { Name: "PIR", Desc: "Parents in room" },
        { Name: "PISS", Desc: "Put in some sugar" },
        { Name: "PITA", Desc: "Pain in the *butt*" },
        { Name: "PKMN", Desc: "Pokemon (online gaming)" },
        { Name: "PL8", Desc: "Plate" },
        { Name: "PLD", Desc: "Played" },
        { Name: "PLMK", Desc: "Please let me know" },
        { Name: "PLS", Desc: "Please" },
        { Name: "PLU", Desc: "People like us" },
        { Name: "PLZ", Desc: "Please" },
        { Name: "PLZTLME", Desc: "Please tell me" },
        { Name: "PM", Desc: "Private Message" },
        { Name: "PMFI", Desc: "Pardon me for interrupting" },
        { Name: "PMFJI", Desc: "Pardon me for jumping in" },
        { Name: "PMSL", Desc: "Pee myself laughing" },
        { Name: "POAHF", Desc: "Put on a happy face" },
        { Name: "POIDH", Desc: "Picture, or it didn't happen" },
        { Name: "POS", Desc: "Parent over shoulder" },
        { Name: "POT", Desc: "Meaning 'potion' (online gaming)" },
        { Name: "POTD", Desc: "Photo of the day (Instagram)" },
        { Name: "POV", Desc: "Point of view" },
        { Name: "POV", Desc: "Privately owned vehicle (originally used to differentiate an individual's vehicle from a military vehicle)" },
        { Name: "PPL", Desc: "People" },
        { Name: "PPU", Desc: "Pending pick-up" },
        { Name: "PRESH", Desc: "Precious" },
        { Name: "PROBS", Desc: "Probably" },
        { Name: "PROLLY", Desc: "Probably" },
        { Name: "PROGGY", Desc: "Meaning computer program" },
        { Name: "PRON", Desc: "Meaning pornography" },
        { Name: "PRT", Desc: "Party" },
        { Name: "PRT", Desc: "Please Retweet" },
        { Name: "PRW", Desc: "People/parents are watching" },
        { Name: "PSA", Desc: "Public Service Announcement" },
        { Name: "PSOS", Desc: "Parent standing over shoulder" },
        { Name: "PSP", Desc: "Playstation Portable" },
        { Name: "PST", Desc: "Please send tell (online gaming)" },
        { Name: "PTFO", Desc: "Pass the *freak* out" },
        { Name: "PTIYPASI", Desc: "Put that in your pipe and smoke it" },
        { Name: "PTL", Desc: "Praise the Lord" },
        { Name: "PTMM", Desc: "Please tell me more" },
        { Name: "PTO", Desc: "Paid time off" },
        { Name: "PTO", Desc: "Personal time off" },
        { Name: "PTO", Desc: "Parent Teacher Organization" },
        { Name: "PUG", Desc: "Pick up group (online gaming)" },
        { Name: "PVE", Desc: "Player vs enemy, Player versus environment (online gaming)" },
        { Name: "PVP", Desc: "Player versus player (online gaming)" },
        { Name: "PWN", Desc: "Meaning 'own'" },
        { Name: "PXT", Desc: "Please explain that" },
        { Name: "PU", Desc: "That stinks!" },
        { Name: "PUKS", Desc: "Pick up kids (SMS)" },
        { Name: "PYT", Desc: "Pretty young thing" },
        { Name: "PZ", Desc: "Peace&nbsp;" },
        { Name: "PZA", Desc: "Pizza" },
        { Name: "Q", Desc: "Queue" },
        { Name: "Q4U", Desc: "(I have a) question for you" },
        { Name: "QC", Desc: "Quality control" },
        { Name: "QFE", Desc: "Question for everyone" },
        { Name: "QFI", Desc: "Quoted for idiocy" },
        { Name: "QFI", Desc: "Quoted for irony" },
        { Name: "QFT", Desc: "Quoted for truth" },
        { Name: "QIK", Desc: "Quick" },
        { Name: "QL", Desc: "Quit laughing" },
        { Name: "QOTD", Desc: "Quote of the day" },
        { Name: "QQ (qq) (Q_Q)", Desc: "Meaning 'crying eyes'" },
        { Name: "QQ", Desc: "Quick question" },
        { Name: "QSL", Desc: "Reply&nbsp;" },
        { Name: "QSO", Desc: "Conversation" },
        { Name: "QT", Desc: "Cutie" },
        { Name: "QTPI", Desc: "Cutie pie" },
        { Name: "R", Desc: "Meaning 'are'" },
        { Name: "R8", Desc: "Rate (SMS)" },
        { Name: "RBAY", Desc: "Right back at you" },
        { Name: "RFN", Desc: "Right *freaking* now" },
        { Name: "RGR", Desc: "Roger (I agree, I understand)" },
        { Name: "RHIP", Desc: "Rank has its privileges" },
        { Name: "RIP", Desc: "Rest in peace" },
        { Name: "RL", Desc: "Real life" },
        { Name: "RLY", Desc: "Really" },
        { Name: "RME", Desc: "Rolling my eyes" },
        { Name: "RMLB", Desc: "Read my lips baby" },
        { Name: "RMMM", Desc: "Read my mail man" },
        { Name: "ROFL", Desc: "Rolling on floor laughing" },
        { Name: "ROFLCOPTER", Desc: "Rolling on floor laughing and spinning around" },
        { Name: "ROFLMAO", Desc: "Rolling on the floor, laughing my *butt* off" },
        { Name: "ROTFL", Desc: "Rolling on the floor laughing" },
        { Name: "ROTFLUTS", Desc: "Rolling on the floor laughing unable to speak" },
        { Name: "RS", Desc: "Runescape (online gaming)" },
        { Name: "RSN", Desc: "Real soon now" },
        { Name: "RT", Desc: "Roger that" },
        { Name: "RT", Desc: "Retweet" },
        { Name: "RTBS", Desc: "Reason to be single" },
        { Name: "RTFM", Desc: "Read the *freaking* manual" },
        { Name: "RTFQ", Desc: "Read the *freaking* question" },
        { Name: "RTHX", Desc: "Meaning 'Thanks for the RT (Retweet)'" },
        { Name: "RTMS", Desc: "Read the manual, stupid" },
        { Name: "RTNTN", Desc: "Retention (email, Government)" },
        { Name: "RTRCTV", Desc: "Retroactive (email, Government)" },
        { Name: "RTRMT", Desc: "Retirement (email, Government)" },
        { Name: "RTSM", Desc: "Read the stupid manual" },
        { Name: "RTWFQ", Desc: "Read the whole *freaking* question" },
        { Name: "RU", Desc: "Are you?" },
        { Name: "RUMOF", Desc: "Are you male or female?" },
        { Name: "RUT", Desc: "Are u (you) there?" },
        { Name: "RUOK", Desc: "Are you okay?" },
        { Name: "RX", Desc: "Regards" },
        { Name: "RW", Desc: "Real world" },
        { Name: "RX", Desc: "Meaning drugs or prescriptions" },
        { Name: "RYB", Desc: "Read your Bible&nbsp;" },
        { Name: "RYO", Desc: "Roll your own" },
        { Name: "RYS", Desc: "Read your screen&nbsp;" },
        { Name: "RYS", Desc: "Are you single?" },
        { Name: "S2R", Desc: "Send to receive (meaning send me your picture to get mine)" },
        { Name: "S2S", Desc: "Sorry to say" },
        { Name: "S4L", Desc: "Spam for life" },
        { Name: "SAL", Desc: "Such a laugh" },
        { Name: "SAT", Desc: "Sorry about that" },
        { Name: "SAVAGE", Desc: "Slang for a shockingly careless expression or response to an event or message" },
        { Name: "SB", Desc: "Snap back (Snapchat)" },
        { Name: "SB", Desc: "Should be" },
        { Name: "SB", Desc: "Smiling back" },
        { Name: "SBIA", Desc: "Meaning Standing back in amazement" },
        { Name: "SBT", Desc: "Sorry 'bout that" },
        { Name: "SC", Desc: "Stay cool" },
        { Name: "SD", Desc: "Sweet dreams" },
        { Name: "SDMB", Desc: "Sweet dreams, my baby" },
        { Name: "SENPAI", Desc: "Meaning someone older than you, someone you look up to" },
        { Name: "SEO", Desc: "Search engine optimization" },
        { Name: "SETE", Desc: "Smiling Ear-to-Ear" },
        { Name: "SELFIE", Desc: "A photo that is taken of oneself for social media sharing" },
        { Name: "SFAIK", Desc: "So far as I know" },
        { Name: "SH", Desc: "Same here" },
        { Name: "SH^", Desc: "Shut up" },
        { Name: "SHID", Desc: "Slapping head in disgust" },
        { Name: "SHIP", Desc: "Slang for 'wishing two people were in a relationship'" },
        { Name: "SICNR", Desc: "Sorry, I could not resist" },
        { Name: "SIG2R", Desc: "Sorry, I got to run" },
        { Name: "SIHTH", Desc: "Stupidity is hard to take" },
        { Name: "SIMYC", Desc: "Sorry I missed your call" },
        { Name: "SIR", Desc: "Strike it rich" },
        { Name: "SIS", Desc: "Snickering in silence" },
        { Name: "SIS", Desc: "Meaning sister" },
        { Name: "SIT", Desc: "Stay in touch" },
        { Name: "SITD", Desc: "Still in the dark" },
        { Name: "SJW", Desc: "Social justice warrior" },
        { Name: "SK8", Desc: "Skate" },
        { Name: "SK8NG", Desc: "Skating" },
        { Name: "SK8R", Desc: "Skater" },
        { Name: "SK8RBOI", Desc: "Skater Boy" },
        { Name: "SLAP", Desc: "Sounds like a plan" },
        { Name: "Slay", Desc: "To succeed at something" },
        { Name: "SM", Desc: "Social media" },
        { Name: "SMAZED", Desc: "Smoky haze (marijuana stoned)" },
        { Name: "SMEXI", Desc: "Combination of sexy and Mexican, used to describe attractive people" },
        { Name: "SMH", Desc: "Shaking my head" },
        { Name: "SMHID", Desc: "Scratching my head in disbelief" },
        { Name: "SNAFU", Desc: "Situation normal all fouled up" },
        { Name: "SNERT", Desc: "Snot nosed egotistical rude teenager" },
        { Name: "SNR", Desc: "Streaks and Recents (Snapchat)" },
        { Name: "SO", Desc: "Significant other" },
        { Name: "SOAB", Desc: "Son of a *B*" },
        { Name: "S'OK", Desc: "Meaning It' (s) okay (ok)" },
        { Name: "SOL", Desc: "Sooner or later" },
        { Name: "SOMY", Desc: "Sick of me yet?" },
        { Name: "SorG", Desc: "Straight or Gay?" },
        { Name: "SOS", Desc: "Meaning help" },
        { Name: "SOS", Desc: "Son of Sam" },
        { Name: "SOT", Desc: "Short of time" },
        { Name: "SOTMG", Desc: "Short of time, must go" },
        { Name: "SOWM", Desc: "Someone with me" },
        { Name: "SPK", Desc: "Speak (SMS)" },
        { Name: "SRSLY", Desc: "Seriously" },
        { Name: "SPST", Desc: "Same place, same time" },
        { Name: "SPTO", Desc: "Spoke to" },
        { Name: "SQ", Desc: "Square" },
        { Name: "SRY", Desc: "Sorry" },
        { Name: "SS", Desc: "So sorry" },
        { Name: "SSDD", Desc: "Same stuff, different day" },
        { Name: "SSIF", Desc: "So stupid it's funny" },
        { Name: "SSINF", Desc: "So stupid it's not funny" },
        { Name: "ST&amp;D", Desc: "Stop texting and drive" },
        { Name: "Stan", Desc: "Meaning a die-hard fan of someone (Snapchat)" },
        { Name: "STFU", Desc: "Shut the *freak* up" },
        { Name: "STR8", Desc: "Straight" },
        { Name: "STW", Desc: "Search the Web" },
        { Name: "SU", Desc: "Shut up" },
        { Name: "SUITM", Desc: "See you in the morning" },
        { Name: "SUL", Desc: "See you later" },
        { Name: "SUP", Desc: "What's up?" },
        { Name: "SUTH", Desc: "So use(d) to haters (Facebook)" },
        { Name: "SUX", Desc: "Meanings sucks or 'it sucks'" },
        { Name: "SUYF", Desc: "Shut up you fool" },
        { Name: "SWAG", Desc: "Meaning free stuff and giveaways from tech tradeshows" },
        { Name: "SWAG", Desc: "Scientific wild *a* guess" },
        { Name: "SWAK", Desc: "Sent (or sealed) with a kiss" },
        { Name: "SWALK", Desc: "Sealed (or sealed) with a loving kiss" },
        { Name: "SWAT", Desc: "Scientific wild *butt* guess" },
        { Name: "SWL", Desc: "Screaming with laughter" },
        { Name: "SWMBO", Desc: "She who must be obeyed. Meaning wife or partner" },
        { Name: "SYL", Desc: "See you later&nbsp;" },
        { Name: "SYS", Desc: "See you soon&nbsp;" },
        { Name: "SYY", Desc: "Shut your yapper" },
        { Name: "T+", Desc: "Think positive" },
        { Name: "T4BU", Desc: "Thanks for being you" },
        { Name: "T:)T", Desc: "Think happy thoughts" },
        { Name: "TA", Desc: "Thanks a lot" },
        { Name: "TAFN", Desc: "That's all for now" },
        { Name: "TAM", Desc: "Tomorro a.m." },
        { Name: "TANK", Desc: "Meaning really strong" },
        { Name: "TANKED", Desc: "Meaning 'owned'" },
        { Name: "TANKING", Desc: "Meaning 'owning'" },
        { Name: "TARFU", Desc: "Things Are Really *fouled* Up." },
        { Name: "TAU", Desc: "Thinking about u (you)" },
        { Name: "TAUMUALU", Desc: "Thinking about you miss you always love you" },
        { Name: "TBAG", Desc: "Process of disgracing a corpse, taunting a fragged/killed player (online gaming)" },
        { Name: "TBBH", Desc: "To be brutally honest" },
        { Name: "TBC", Desc: "To be continued" },
        { Name: "TBD", Desc: "To be determined" },
        { Name: "TBH", Desc: "To be honest" },
        { Name: "TBL", Desc: "Text back later" },
        { Name: "TBT", Desc: "Throwback Thursday" },
        { Name: "TC", Desc: "Take care" },
        { Name: "TCB", Desc: "Take care of business" },
        { Name: "TCOY", Desc: "Take care of yourself" },
        { Name: "TD", Desc: "Tower defense (online gaming)" },
        { Name: "TD2M", Desc: "Talk dirty to me" },
        { Name: "TDTM", Desc: "Talk dirty to me" },
        { Name: "TEA", Desc: "Meaning gossip" },
        { Name: "TFF", Desc: "Too *freaking* funny" },
        { Name: "TFS", Desc: "Thanks for sharing" },
        { Name: "TFTF", Desc: "Thanks for the follow" },
        { Name: "TFTI", Desc: "Thanks for the invitation" },
        { Name: "TFTT", Desc: "Thanks for this tweet" },
        { Name: "TG", Desc: "Thank goodness" },
        { Name: "TGIF", Desc: "Thank God it's Friday" },
        { Name: "THNQ", Desc: "Thank-you (SMS)" },
        { Name: "THNX", Desc: "Thanks" },
        { Name: "THOT", Desc: "That wh*re over there" },
        { Name: "THT", Desc: "Think happy thoughts" },
        { Name: "THX", Desc: "Thanks" },
        { Name: "TIA", Desc: "Thanks in advance" },
        { Name: "TIAD", Desc: "Tomorrow is another day" },
        { Name: "TIC", Desc: "Tongue-in-cheek" },
        { Name: "TIL", Desc: "Today I learned" },
        { Name: "TILIS", Desc: "Tell it like it is" },
        { Name: "TIR", Desc: "Teacher in room" },
        { Name: "TLK2UL8R", Desc: "Talk to you later" },
        { Name: "TL", Desc: "Too long" },
        { Name: "TL;DR", Desc: "Too long; didn't read" },
        { Name: "TM", Desc: "Trust me" },
        { Name: "TMA", Desc: "Take my advice" },
        { Name: "TMB", Desc: "Text me back" },
        { Name: "TMB", Desc: "Tweet me back" },
        { Name: "TMI", Desc: "Too much information" },
        { Name: "TMOT", Desc: "Trust me on this" },
        { Name: "TMTH", Desc: "Too much to handle" },
        { Name: "TMYL", Desc: "Tell me your location" },
        { Name: "TMWFI", Desc: "Take my word for it" },
        { Name: "TNSTAAFL", Desc: "There's no such thing as a free lunch" },
        { Name: "TNT", Desc: "Til next time" },
        { Name: "TOJ", Desc: "Tears of joy" },
        { Name: "TOS", Desc: "Terms of service" },
        { Name: "TOTES", Desc: "Totally" },
        { Name: "TOU", Desc: "Thinking of you" },
        { Name: "TOY", Desc: "Thinking of you" },
        { Name: "TPM", Desc: "Tomorrow p.m." },
        { Name: "TPTB", Desc: "The powers that be" },
        { Name: "TQ", Desc: "Te quiero / I love you (Spanish SMS)" },
        { Name: "TSH", Desc: "Tripping so hard" },
        { Name: "TSNF", Desc: "That's so not fair" },
        { Name: "TSTB", Desc: "The sooner, the better" },
        { Name: "TT", Desc: "Trending topic" },
        { Name: "TTFN", Desc: "Ta ta for now" },
        { Name: "TTLY", Desc: "Totally" },
        { Name: "TTTT", Desc: "These things take time" },
        { Name: "TTUL", Desc: "Talk to you later" },
        { Name: "TU", Desc: "Thank you" },
        { Name: "TUI", Desc: "Turning you in" },
        { Name: "TURNT", Desc: "Meaning excitement, turned up" },
        { Name: "TWSS", Desc: "That's what she said" },
        { Name: "TTG", Desc: "Time to go" },
        { Name: "TTYAFN", Desc: "Talk to you awhile from now" },
        { Name: "TTYL", Desc: "Talk to you later" },
        { Name: "TTYS", Desc: "Talk to you soon" },
        { Name: "TY", Desc: "Thank you" },
        { Name: "TYFC", Desc: "Thank you for charity (online gaming)" },
        { Name: "TYFYC", Desc: "Thank you for your comment" },
        { Name: "TYS", Desc: "Told you so" },
        { Name: "TYT", Desc: "Take your time" },
        { Name: "TYSO", Desc: "Thank you so much" },
        { Name: "TYAFY", Desc: "Thank you and *freak* you" },
        { Name: "TYVM", Desc: "Thank you very much" },
        { Name: "TX", Desc: "Thanks" },
        { Name: "^URS", Desc: "Up yours" },
        { Name: "UCMU", Desc: "You crack me up" },
        { Name: "UDI", Desc: "Unidentified drinking injury (meaning bruise, scratch, ache and so on)" },
        { Name: "UDM", Desc: "U (You) da (the) man" },
        { Name: "UDS", Desc: "Ugly domestic scene" },
        { Name: "UFB", Desc: "Un *freaking* believable" },
        { Name: "UFN", Desc: "Until further notice" },
        { Name: "UFWM", Desc: "You *freaking* with me?" },
        { Name: "UGTBK", Desc: "You've got to be kidding" },
        { Name: "UHGTBSM", Desc: "You have got to be s#$t*ing me!" },
        { Name: "UKTR", Desc: "You know that's right" },
        { Name: "UL", Desc: "Upload" },
        { Name: "U-L", Desc: "Meaning 'You will'" },
        { Name: "UNA", Desc: "Use no acronyms" },
        { Name: "UN4TUN8", Desc: "Unfortunate" },
        { Name: "UNBLEFBLE", Desc: "Unbelievable" },
        { Name: "UNCRTN", Desc: "Uncertain" },
        { Name: "UNPC", Desc: "Un- (not) politically correct" },
        { Name: "UOK", Desc: "(Are) You ok?" },
        { Name: "UR", Desc: "You are / You're" },
        { Name: "UR2YS4ME", Desc: "You are too wise for me" },
        { Name: "URA*", Desc: "You are a star" },
        { Name: "URH", Desc: "You are hot (U R Hot)" },
        { Name: "URSKTM", Desc: "You are so kind to me" },
        { Name: "URTM", Desc: "You are the man" },
        { Name: "URW", Desc: "You are welcome" },
        { Name: "USBCA", Desc: "Until something better comes along" },
        { Name: "USU", Desc: "Usually" },
        { Name: "UT", Desc: "Unreal Tournament (online gaming)" },
        { Name: "UT2L", Desc: "You take too long" },
        { Name: "UTM", Desc: "You tell me" },
        { Name: "UV", Desc: "Unpleasant visual" },
        { Name: "UW", Desc: "You're welcome" },
        { Name: "UX", Desc: "User experience" },
        { Name: "V", Desc: "Very" },
        { Name: "VAT", Desc: "Value added tax" },
        { Name: "VBL", Desc: "Visible bra line" },
        { Name: "VBS", Desc: "Very big smile" },
        { Name: "VC", Desc: "Voice chat" },
        { Name: "VEG", Desc: "Very evil grin" },
        { Name: "VFF", Desc: "Very freaking funny" },
        { Name: "VFM", Desc: "Value for money" },
        { Name: "VGC", Desc: "Very good condition" },
        { Name: "VGG", Desc: "Very good game (online gaming)" },
        { Name: "VGH", Desc: "Very good hand (online gaming)" },
        { Name: "VIP", Desc: "Very important person" },
        { Name: "VM", Desc: "Voice mail" },
        { Name: "VN", Desc: "Very nice" },
        { Name: "VNH", Desc: "Very nice hand (online gaming)" },
        { Name: "VoIP", Desc: "Voice over Internet Protocol" },
        { Name: "VRY", Desc: "Very" },
        { Name: "VSC", Desc: "Very soft chuckle" },
        { Name: "VSF", Desc: "Very sad face" },
        { Name: "VWD", Desc: "Very well done (online gaming)" },
        { Name: "VWP", Desc: "Very well played (online gaming)" },
        { Name: "W@", Desc: "What?" },
        { Name: "W/", Desc: "With" },
        { Name: "W/B", Desc: "Welcome back" },
        { Name: "W3", Desc: "WWW (Web address)" },
        { Name: "W8", Desc: "Wait" },
        { Name: "WAH", Desc: "Working at home" },
        { Name: "WAJ", Desc: "What a jerk" },
        { Name: "WAM", Desc: "Wait a minute" },
        { Name: "WAN2", Desc: "Want to? (SMS)" },
        { Name: "WAN2TLK", Desc: "Want to talk" },
        { Name: "WAREZ", Desc: "Meaning pirated (illegally gained) software" },
        { Name: "WAS", Desc: "Wait a second" },
        { Name: "WAS", Desc: "Wild *a* guess" },
        { Name: "WAT", Desc: "What" },
        { Name: "WAWA", Desc: "Where are we at?" },
        { Name: "WAYF", Desc: "Where are you from?" },
        { Name: "W/B", Desc: "Write back" },
        { Name: "WB", Desc: "Welcome back" },
        { Name: "WBS", Desc: "Write back soon" },
        { Name: "WBU", Desc: "What about you?" },
        { Name: "WC", Desc: "Welcome" },
        { Name: "WC", Desc: "Who cares" },
        { Name: "WCA", Desc: "Who cares anyway" },
        { Name: "W/E", Desc: "Whatever" },
        { Name: "W/END", Desc: "Weekend" },
        { Name: "WE", Desc: "Whatever" },
        { Name: "WEBO", Desc: "Webopedia" },
        { Name: "WEEBO", Desc: "Describes a person obsessed with of Japanese culture" },
        { Name: "WEP", Desc: "Weapon (online gaming)" },
        { Name: "WH5", Desc: "Who, what, when, where, why" },
        { Name: "WHATEVES", Desc: "Whatever" },
        { Name: "WIBNI", Desc: "Wouldn't it be nice if" },
        { Name: "WDALYIC", Desc: "Who died and left you in charge" },
        { Name: "WDYK", Desc: "What do you know?" },
        { Name: "WDYT", Desc: "What do you think?" },
        { Name: "WGACA", Desc: "What do you think?" },
        { Name: "WIIFM", Desc: "What's in it for me?" },
        { Name: "WISP", Desc: "Winning is so pleasurable" },
        { Name: "WITP", Desc: "What is the point?" },
        { Name: "WITW", Desc: "What in the world" },
        { Name: "WIU", Desc: "Wrap it up" },
        { Name: "WK", Desc: "Week" },
        { Name: "WKD", Desc: "Weekend" },
        { Name: "WRT", Desc: "With regard to" },
        { Name: "WL", Desc: "Whatta loser" },
        { Name: "W/O", Desc: "Without" },
        { Name: "WOA", Desc: "Work of Art" },
        { Name: "WOKE", Desc: "Slang for people who are aware of current social issues, and politics" },
        { Name: "WOMBAT", Desc: "Waste of money, brains and time" },
        { Name: "WOW", Desc: "World of Warcraft (online gaming)" },
        { Name: "WRK", Desc: "Work" },
        { Name: "WRU", Desc: "Where are you?" },
        { Name: "WRU@", Desc: "Where are you at?" },
        { Name: "WRUD", Desc: "What are you doing?" },
        { Name: "WTB", Desc: "Want to buy (online gaming)" },
        { Name: "WTF", Desc: "What the *freak* ?" },
        { Name: "WTFE", Desc: "What the *freak* ever" },
        { Name: "WTFO", Desc: "What the *freak* ?, over." },
        { Name: "WTG", Desc: "Way to go" },
        { Name: "WTGP", Desc: "Want to go private (talk out of public chat area)" },
        { Name: "WTH", Desc: "What the heck?" },
        { Name: "WTM", Desc: "Who's the man?" },
        { Name: "WTS", Desc: "Want to sell? (online gaming)" },
        { Name: "WTT", Desc: "Want to trade? (online gaming)" },
        { Name: "WU", Desc: "What's up?" },
        { Name: "WUCIWUG", Desc: "What you see is what you get" },
        { Name: "WUF", Desc: "Where are you from?" },
        { Name: "WUP", Desc: "What's up?" },
        { Name: "WUT", Desc: "Meaning 'what'" },
        { Name: "WUW", Desc: "What u (you) want?" },
        { Name: "WUU2", Desc: "What are you up to?" },
        { Name: "WUZ", Desc: "Was" },
        { Name: "WWJD", Desc: "What would Jesus do?" },
        { Name: "WWJD", Desc: "What Would Judd Do? (Artist Donald Judd, who was known to do things in his own compulsive way.)" },
        { Name: "WWNC", Desc: "Will wonders never cease" },
        { Name: "WWYC", Desc: "Write when you can" },
        { Name: "WYCM", Desc: "Will you call me?" },
        { Name: "WYD", Desc: "What (are) you doing?" },
        { Name: "WYGAM", Desc: "When you get a minute" },
        { Name: "WYHAM", Desc: "When you have a minute" },
        { Name: "WYLEI", Desc: "When you least expect it" },
        { Name: "WYSIWYG", Desc: "What you see is what you get&nbsp;" },
        { Name: "WYWH", Desc: "Wish you were here" },
        { Name: "X-1-10", Desc: "Meaning 'Exciting'" },
        { Name: "X", Desc: "Kiss" },
        { Name: "X!", Desc: "Meaning 'a typical woman'" },
        { Name: "XD", Desc: "Meaning 'really hard laugh' (where D is a smiley mouth)" },
        { Name: "XD", Desc: "Meaning a 'devilish smile'" },
        { Name: "XME", Desc: "Excuse Me" },
        { Name: "XOXOXO", Desc: "Hugs &amp; Kisses" },
        { Name: "XLNT", Desc: "Excellent&nbsp;" },
        { Name: "XLR8", Desc: "Meaning 'faster' or 'going faster'" },
        { Name: "XPOST", Desc: "Meaning Cross-post. A link posted to a subreddit that was already shared on a different subreddit (Reddit)" },
        { Name: "XYL", Desc: "Ex-young lady, meaning wife. (amateur radio)&nbsp;" },
        { Name: "XYZ", Desc: "Examine your zipper" },
        { Name: "Y?", Desc: "Why?" },
        { Name: "Y", Desc: "Meaning Yawn" },
        { Name: "Y2K", Desc: "You're too kind" },
        { Name: "YA", Desc: "Your" },
        { Name: "YAA", Desc: "Yet another acronym" },
        { Name: "YABA", Desc: "Yet another bloody acronym" },
        { Name: "YARLY", Desc: "Ya, really?" },
        { Name: "YAS", Desc: "Meaning 'praise'" },
        { Name: "YBIC", Desc: "Your brother in Christ" },
        { Name: "YBS", Desc: "You'll be sorry" },
        { Name: "YCDBWYCID", Desc: "You can't do business when your computer is down" },
        { Name: "YCHT", Desc: "You can have them" },
        { Name: "YCLIU", Desc: "You can look it up" },
        { Name: "YCMU", Desc: "You crack me up" },
        { Name: "YCT", Desc: "Meaning Your comment to?" },
        { Name: "YD", Desc: "Yesterday" },
        { Name: "YEET", Desc: "Meaning excitement, approval or display of energy (i.e. throwing something)" },
        { Name: "YF", Desc: "Wife" },
        { Name: "YG", Desc: "Young gentleman" },
        { Name: "YGG", Desc: "You go girl" },
        { Name: "YGTBKM", Desc: "You've got to be kidding me" },
        { Name: "YGTR", Desc: "You got that right" },
        { Name: "YHBT", Desc: "You have been trolled" },
        { Name: "YHBW", Desc: "You have been warned" },
        { Name: "YHL", Desc: "You have lost" },
        { Name: "YIU", Desc: "Yes, I understand" },
        { Name: "YKW", Desc: "You know what" },
        { Name: "YKWYCD", Desc: "You know what you can do" },
        { Name: "YL", Desc: "Young lady" },
        { Name: "YMMV", Desc: "Your mileage may vary" },
        { Name: "YNK", Desc: "You never know" },
        { Name: "YOLO", Desc: "You only live once" },
        { Name: "YR", Desc: "Your" },
        { Name: "YR", Desc: "Yeah right" },
        { Name: "YRYOCC", Desc: "You're running your own cuckoo clock" },
        { Name: "YSIC", Desc: "Your sister in Christ" },
        { Name: "YSYD", Desc: "Yeah sure you do" },
        { Name: "YT", Desc: "YouTube" },
        { Name: "YT", Desc: "You there?" },
        { Name: "YTB", Desc: "You're the best" },
        { Name: "YTB", Desc: "Youth talk back" },
        { Name: "YTTL", Desc: "You take too long" },
        { Name: "YTG", Desc: "You're the greatest" },
        { Name: "YW", Desc: "You're welcome" },
        { Name: "YWHNB", Desc: "Yes, we have no bananas" },
        { Name: "YWHOL", Desc: "Yelling 'woohoo' out loud" },
        { Name: "YWSYLS", Desc: "You win some, you lose some" },
        { Name: "YYSSW", Desc: "Yeah, yeah, sure, sure, whatever" },
        { Name: "Z", Desc: "Zero" },
        { Name: "Z", Desc: "Z's are calling (meaning going to bed/sleep)" },
        { Name: "Z", Desc: "Meaning 'Said'" },
        { Name: "Z%", Desc: "Zoo" },
        { Name: "ZH", Desc: "Sleeping Hour" },
        { Name: "ZOMG", Desc: "Used in World of Warcraft to mean OMG (Oh My God)" },
        { Name: "ZOT", Desc: "Zero tolerance" },
        { Name: "ZUP", Desc: "Meaning 'What's up?'" },
        { Name: "ZZZZ", Desc: "Sleeping (or bored)" }

      ]);
    });
};

/*
=CONCATENATE("{Name: """,A1)
=CONCATENATE("{Name: """,A1,""", Desc:")

=CONCATENATE("{Name: """,A1,""", Desc:""", B1, """},")
*/
